development:
  default_web_url: "http://localhost:3000"
  zoom:
    heqifatihaputri@gmail.com:
      api_key: 'vn44mkIrQo2k9dnsr7f29g'
      api_secret: '88c0MBBA5AGnDgV11cRT2qsUmTbQrVdzoJZ0'
      im_chat: 'eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJxRlFpYnJWX1JEcXIyMTlVOUw4Rmt3In0.olB6IwaClsV6j3v_bWeJSW2WoF6Rfr3l5xZoIRyBLiA'
  xendit_secret_key: "xnd_development_CR8zuvQNsxtbWNV9fIEHfNWLt3S0alC5X27AZWYbIudvkPill0oIZzQDKPTbM4"